### ISSUE TITLE
Outline_Shader.tres missing

### ISSUE THREAD

**Issue by bluebarnacles** [Reneator/godot-skill-tree#1]
Skill_Tree_Node.tscn and Skill_Tree_Test.tscn refer to Outline_Shader.tres, but it isn't included in the repo

Thanks for making this!

**Comment by Reneator** [comment]
Just commited it, thank you for pointing it out!

And happy to help!

**Comment by Reneator** [comment]
And go ahead and create some issues tickets if you are interested in certain kinds of features in the skill-tree, then i would go about and try to implement them and then i can explain how they work if needed/wanted

**Comment by Reneator** [comment]
I noticed, that i wasnt even using the outline-shader in the example, as the shader wouldnt show, as the icons are the same size as the sprite-äsize itself, as godot doesnt draw shader-effects outside the bounds of the sprite.

Closing this issue. And Thanks!
